// Transaction History Hook
// Generated by [N]skills

'use client';

import { useQuery } from '@tanstack/react-query';
import { useAccount } from 'wagmi';
import { duneClient, type Transaction } from '@/lib/dune-client';

export interface UseTransactionHistoryParams {
  address?: string;
  blockchain?: string;
  limit?: number;
  enabled?: boolean;
}

export function useTransactionHistory(params?: UseTransactionHistoryParams) {
  const { address: connectedAddress } = useAccount();
  const targetAddress = params?.address ?? connectedAddress;

  return useQuery({
    queryKey: ['dune-tx-history', targetAddress, params?.blockchain, params?.limit],
    queryFn: () => duneClient.getTransactionHistory(
      targetAddress!,
      params?.blockchain ?? 'arbitrum',
      params?.limit ?? 100
    ),
    enabled: !!targetAddress && (params?.enabled ?? true),
    staleTime: 60000,
  });
}