// Transaction History Component
// Generated by [N]skills

'use client';

import { useTransactionHistory } from '@/hooks/useTransactionHistory';

interface TransactionHistoryProps {
  address?: string;
  blockchain?: string;
  limit?: number;
  className?: string;
}

export function TransactionHistory({ address, blockchain, limit, className }: TransactionHistoryProps) {
  const { data: transactions, isLoading, error } = useTransactionHistory({ 
    address, 
    blockchain, 
    limit 
  });

  if (isLoading) {
    return (
      <div className={`p-4 rounded-xl bg-zinc-800/50 border border-zinc-700/50 ${className}`}>
        <div className="animate-pulse space-y-3">
          {[1, 2, 3].map(i => (
            <div key={i} className="h-12 bg-zinc-700 rounded" />
          ))}
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className={`p-4 rounded-xl bg-zinc-800/50 border border-red-500/30 ${className}`}>
        <p className="text-red-400 text-sm">Failed to load transactions</p>
      </div>
    );
  }

  return (
    <div className={`p-4 rounded-xl bg-zinc-800/50 border border-zinc-700/50 ${className}`}>
      <h3 className="text-sm font-medium text-zinc-400 mb-4">Recent Transactions</h3>
      <div className="space-y-2">
        {transactions?.slice(0, 10).map((tx, i) => (
          <div key={i} className="flex items-center justify-between p-2 rounded-lg bg-zinc-900/50">
            <div className="flex items-center gap-2">
              <span className={`w-2 h-2 rounded-full ${
                tx.direction === 'sent' ? 'bg-red-400' :
                tx.direction === 'received' ? 'bg-green-400' : 'bg-yellow-400'
              }`} />
              <span className="text-xs text-zinc-500 font-mono">
                {tx.hash.slice(0, 8)}...
              </span>
            </div>
            <span className={`text-sm ${
              tx.direction === 'sent' ? 'text-red-400' : 'text-green-400'
            }`}>
              {tx.direction === 'sent' ? '-' : '+'}{tx.value.toFixed(4)} ETH
            </span>
          </div>
        ))}
      </div>
    </div>
  );
}

export default TransactionHistory;